### ISSUE TITLE
TypeError on POST in v.1.0.11/12

### ISSUE THREAD

**Issue by brunnurs** [seglo/connect-prism#59]
**Issue**
We use prism in proxy mode to redirect REST requests form an angular front end to a back end in docker. When doing a POST in the new version _1.0.12_ (or _1.0.11_)  we got the following error:

```js
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:218:9)
    at new Buffer (buffer.js:65:10)
    at placeholder\node_modules\connect-prism\lib\modes\proxy.js:19:28
```

**Reproduce**
```javascript
curl 'http://localhost:8088/bpm/activiti/save' -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"taskId":"50584","properties":[{"id":"abort_video","value":false}]}'
```

**Reason**
In [api.js](https://github.com/seglo/connect-prism/blob/master/lib/services/api.js#L41) req.body is set to an object: 
```javascript
      try {
        req.body = JSON.parse(body);
      } catch (err) {}
```
Now later in [proxy.js](https://github.com/seglo/connect-prism/blob/master/lib/modes/proxy.js#L19), the same req.body is a constructor parameter for a Buffer object.

```javascript
 if (req.bodyRead) {
      //re-stream the request body, because it has already been consumed
      req.removeAllListeners('data');
      req.removeAllListeners('end');

      process.nextTick(function() {
        if (req.body) {
          req.emit('data', new Buffer(req.body))
        }
        req.emit('end')
      });
    }
```
But a buffer can not get initialized with an object (see error).
The Bug only appears in v 1.0.11/1.0.12, with v 1.0.6 the POST never runs into this error (aka never reaches this line in proxy.js). 

I'm not sure which change caused the problem, but my guess would be [Support hashFullRequest for mockrecord mode](https://github.com/seglo/connect-prism/commit/0f71500db834c1701f2cab153c9e723c45345873)

We temporary downgrade the prism version to 1.0.6, but it would be nice to use the latest one. Let me know if I can help!

**Comment by Psidium** [comment]
We have this problem as well, for now, we are using `grunt-connect-proxy` for proxying and `grunt-connect-prism` for cached requests.

**Comment by seglo** [comment]
Hey @brunnurs , it may take me awhile to get to this.  Best way to help would be to submit a PR.  If it satisfies the existing testsuite I'll merge it in.

**Comment by morioust** [comment]
I created a pull request https://github.com/seglo/connect-prism/pull/63 that hopefully fixes the issue.

The issue seemed to be the api component optimistically parsing and persisting the body even when not required:

1. The API handler gets called for every incoming request ([index.js](https://github.com/seglo/connect-prism/blob/master/index.js#L45)):
```
middleware: function(req, res, next) {
  if (!api.handleRequest(req, res) && !httpEvents.handleRequest(req, res)) {
    next();
  }
}
```

2. The API handler parses the JSON body, even if the request isn't an API request ([api.js](https://github.com/seglo/connect-prism/blob/master/lib/services/api.js#L40)):
```
  // Handle an api request to /_prism
  this.handleRequest = function(req, res, next) {
    prismUtils.getBody(req, function(body) {
      // director should parse JSON for me!
      // https://github.com/flatiron/director/issues/275
      try {
        req.body = JSON.parse(body);
      } catch (err) {}
    });
    return router.dispatch(req, res
      /* *** Can't handle error and close response if this isn't a valid request, function(err) {
      if (err) {
        console.log('api returning 404');
        res.writeHead(404);
        res.end();
      }
    }*/
    );
  };
```

This causes problems later when the body contains an object instead of a string.

The pull request fixes this by parsing the body for use by the API only if the request is an API request.

Caveat: I couldn't quickly come up with a good new test case that covers this issue. Since the API middleware is chained in front of the proxy middleware at top level in the `index.js`, I guess one would need to base the test case on that.

I'm in a bit of a rush now, but maybe I can create one later.

The previous tests run through without regressions.
