### ISSUE TITLE
[question] Is it possible to remove dependency on di?

### ISSUE THREAD

**Issue by cthrax** [seglo/connect-prism#60]
Hey,

Just opening up the discussion on removing the di dependency. It depends on a very old version of traceur that is causing problems in other plugins when running through gulp, due to a bug in traceur at that version (0.0.33 vs current version of 0.0.111). I've got some workarounds for fixing it, but not working around might be a plus too.

No biggie if not, love the tool, thanks for the work!

**Comment by seglo** [comment]
Hey @cthrax,

It's good to hear from you again.  I used di on a bet that it would be further developed and adopted into angular.js 2.0.  I'm not really doing any node.js these days, and even less front end work with angular, so I don't really know what happened with that project.  I realize it is an old version and I would be inclined to remove or replace it, but it would require a bit of an investment for me to do so.  

Since you're a longtime and active user would you be open to being added as a collaborator to help keep this project alive?

Regards,
Sean

**Comment by cthrax** [comment]
Sure, I can certainly contribute.

I had investigated a little bit what was going on with di and it's basically stalled right now because they don't have a standalone version for non-angular apps, at least according to the most recent activity on the repo. So it's an angular only thing.

I'll happily look at removing di as I get some free time.

Thanks again for your contributions, hopefully if I do I make some contributions of my own, you'll be able to cast an eye over them.

**Comment by seglo** [comment]
Cool.  I added you as a collaborator so feel free to merge in PR's.  We can coordinate on when a release to npm is necessary.

**Comment by seglo** [comment]
Resolved with #61

**Comment by seglo** [comment]
BTW, released 1.0.13 with the fix!

**Comment by cthrax** [comment]
Awesome! Thanks for the help!
